# Generated by Django 2.1.7 on 2019-03-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contactmodel',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
