# Generated by Django 2.1.7 on 2019-03-12 18:29

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path),
        ),
    ]
