# Generated by Django 2.1.7 on 2019-03-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190312_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
