# Generated by Django 2.1.7 on 2019-03-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productmodel_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
